name: Release
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          server-id: github
          server-username: MAVEN_REPO_SERVER_USERNAME
          server-password: MAVEN_REPO_SERVER_PASSWORD

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven Release
        run: >
          ./mvnw -B release:prepare release:perform
          "-Dusername=$GITHUB_ACTOR"
          "-Dpassword=$GITHUB_TOKEN"
          "-Darguments=$MAVEN_RELEASE_ARGUMENTS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_REPO_SERVER_USERNAME: emergentbot
          MAVEN_REPO_SERVER_PASSWORD: ${{ secrets.MAVEN_REPO_SERVER_PASSWORD }}
          MAVEN_RELEASE_ARGUMENTS: >
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/pwoodworth/maven-repository
            -Pdistribution